# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f04283ab4f37410a4cb584ff677587555af64bfe716995f36fdc9c97750ac3b09e4fac5d227131df64ddb644de898af95178e7c91742b4e15e0f6eb8bda965

test:
  secret_key_base: 16b96f3613b133ea7f9de93fd4dc41b2f81c2aa599a4d75d2128bef1e24891ae10d5f5f55140773b070acb1db606c761e9cd2c53e5e6b081eea61918cd840837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
